import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { io } from 'socket.io-client/debug'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const socket = io('http://localhost:3001');

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" data-theme="dark">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
